
*******2017-05-10 22:38:36.296000*************
      5973 records has been stored in MySQL 
*******get_content urlopen error record by get_content 2017-05-10 22:38:44.523000*************
2017-05-10 22:38:44.523000
Traceback (most recent call last):
  File "E:\git\spider\html_downloader.py", line 34, in get_content
    response = urllib2.urlopen(request,timeout=10)
  File "G:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "G:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "G:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "G:\Python27\lib\urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "G:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python27\lib\urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "G:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "G:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "G:\Python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "G:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

*******2017-05-10 22:41:44.527000*************
      5973 records has been stored in MySQL 
*******get_content urlopen error record by get_content 2017-05-11 08:17:35.918000*************
2017-05-11 08:17:35.918000
Traceback (most recent call last):
  File "E:\git\spider\html_downloader.py", line 34, in get_content
    response = urllib2.urlopen(request,timeout=10)
  File "G:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "G:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "G:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "G:\Python27\lib\urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "G:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python27\lib\urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "G:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "G:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "G:\Python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "G:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

*******get_content urlopen error record by get_content 2017-05-11 08:20:45.209000*************
2017-05-11 08:20:45.209000
Traceback (most recent call last):
  File "E:\git\spider\html_downloader.py", line 34, in get_content
    response = urllib2.urlopen(request,timeout=10)
  File "G:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "G:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "G:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "G:\Python27\lib\urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "G:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python27\lib\urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "G:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "G:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "G:\Python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "G:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

*******get_content urlopen error record by get_content 2017-05-11 08:26:57.914000*************
2017-05-11 08:26:57.914000
Traceback (most recent call last):
  File "E:\git\spider\html_downloader.py", line 34, in get_content
    response = urllib2.urlopen(request,timeout=10)
  File "G:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "G:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "G:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "G:\Python27\lib\urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "G:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python27\lib\urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "G:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "G:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "G:\Python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "G:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

*******get_content urlopen error record by get_content 2017-05-11 08:36:06.443000*************
2017-05-11 08:36:06.443000
Traceback (most recent call last):
  File "E:\git\spider\html_downloader.py", line 34, in get_content
    response = urllib2.urlopen(request,timeout=10)
  File "G:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "G:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "G:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "G:\Python27\lib\urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "G:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python27\lib\urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "G:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "G:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "G:\Python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "G:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
