
*******2017-05-15 17:34:59.904000*************
         0 records has been stored in MySQL 
*******2017-05-15 17:38:33.656000*************
 no new datas have been crawed :http://xm.anjuke.com/sale/p37-rd1/?kw=%E9%87%91%E9%B8%A1%E4%BA%AD%E8%8A%B1%E5%9B%AD%E5%B0%8F%E5%8C%BA&from_url=kw_final#filtersort. 

*******2017-05-15 17:40:02.981000*************
       148 records has been stored in MySQL 
*******2017-05-15 17:40:33.667000*************
       148 records has been stored in MySQL 
*******2017-05-15 17:41:55.554000*************
       148 records has been stored in MySQL 
*******get_content urlopen error record by get_content 2017-05-15 17:42:23.057000*************
2017-05-15 17:42:23.057000
Traceback (most recent call last):
  File "E:\git\spider\html_downloader.py", line 34, in get_content
    response = urllib2.urlopen(request,timeout=10)
  File "G:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "G:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "G:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "G:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "G:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11004] getaddrinfo failed>

*******get_content urlopen error record by get_content 2017-05-15 17:43:02.899000*************
2017-05-15 17:43:02.899000
Traceback (most recent call last):
  File "E:\git\spider\html_downloader.py", line 34, in get_content
    response = urllib2.urlopen(request,timeout=10)
  File "G:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "G:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "G:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "G:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "G:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11004] getaddrinfo failed>

*******get_content urlopen error record by get_content 2017-05-15 17:43:22.259000*************
2017-05-15 17:43:22.259000
Traceback (most recent call last):
  File "E:\git\spider\html_downloader.py", line 34, in get_content
    response = urllib2.urlopen(request,timeout=10)
  File "G:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "G:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "G:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "G:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "G:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11004] getaddrinfo failed>

*******get_content urlopen error record by get_content 2017-05-15 17:43:42.600000*************
2017-05-15 17:43:42.600000
Traceback (most recent call last):
  File "E:\git\spider\html_downloader.py", line 34, in get_content
    response = urllib2.urlopen(request,timeout=10)
  File "G:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "G:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "G:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "G:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "G:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11004] getaddrinfo failed>

*******get_content urlopen error record by get_content 2017-05-15 17:44:14.736000*************
2017-05-15 17:44:14.736000
Traceback (most recent call last):
  File "E:\git\spider\html_downloader.py", line 34, in get_content
    response = urllib2.urlopen(request,timeout=10)
  File "G:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "G:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "G:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "G:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "G:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11004] getaddrinfo failed>

*******2017-05-15 17:44:28.792000*************
       148 records has been stored in MySQL 
*******get_content urlopen error record by get_content 2017-05-15 17:44:48.151000*************
2017-05-15 17:44:48.151000
Traceback (most recent call last):
  File "E:\git\spider\html_downloader.py", line 34, in get_content
    response = urllib2.urlopen(request,timeout=10)
  File "G:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "G:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "G:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "G:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "G:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11004] getaddrinfo failed>

*******get_content urlopen error record by get_content 2017-05-15 17:45:31.098000*************
2017-05-15 17:45:31.098000
Traceback (most recent call last):
  File "E:\git\spider\html_downloader.py", line 34, in get_content
    response = urllib2.urlopen(request,timeout=10)
  File "G:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "G:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "G:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "G:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "G:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11004] getaddrinfo failed>

*******get_content urlopen error record by get_content 2017-05-15 17:46:02.938000*************
2017-05-15 17:46:02.938000
Traceback (most recent call last):
  File "E:\git\spider\html_downloader.py", line 34, in get_content
    response = urllib2.urlopen(request,timeout=10)
  File "G:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "G:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "G:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "G:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "G:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11004] getaddrinfo failed>

*******get_content urlopen error record by get_content 2017-05-15 17:46:42.890000*************
2017-05-15 17:46:42.890000
Traceback (most recent call last):
  File "E:\git\spider\html_downloader.py", line 34, in get_content
    response = urllib2.urlopen(request,timeout=10)
  File "G:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "G:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "G:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "G:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "G:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11004] getaddrinfo failed>

*******get_content urlopen error record by get_content 2017-05-15 17:47:43.386000*************
2017-05-15 17:47:43.386000
Traceback (most recent call last):
  File "E:\git\spider\html_downloader.py", line 34, in get_content
    response = urllib2.urlopen(request,timeout=10)
  File "G:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "G:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "G:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "G:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "G:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11004] getaddrinfo failed>

*******get_content urlopen error record by get_content 2017-05-15 17:48:10.858000*************
2017-05-15 17:48:10.858000
Traceback (most recent call last):
  File "E:\git\spider\html_downloader.py", line 34, in get_content
    response = urllib2.urlopen(request,timeout=10)
  File "G:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "G:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "G:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "G:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "G:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11004] getaddrinfo failed>

*******get_content urlopen error record by get_content 2017-05-15 17:49:37.501000*************
2017-05-15 17:49:37.501000
Traceback (most recent call last):
  File "E:\git\spider\html_downloader.py", line 34, in get_content
    response = urllib2.urlopen(request,timeout=10)
  File "G:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "G:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "G:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "G:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "G:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11004] getaddrinfo failed>

*******2017-05-15 17:49:50.730000*************
       148 records has been stored in MySQL 
*******get_content urlopen error record by get_content 2017-05-15 17:50:11.088000*************
2017-05-15 17:50:11.088000
Traceback (most recent call last):
  File "E:\git\spider\html_downloader.py", line 34, in get_content
    response = urllib2.urlopen(request,timeout=10)
  File "G:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "G:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "G:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "G:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "G:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11004] getaddrinfo failed>

*******get_content urlopen error record by get_content 2017-05-15 17:51:46.139000*************
2017-05-15 17:51:46.139000
Traceback (most recent call last):
  File "E:\git\spider\html_downloader.py", line 34, in get_content
    response = urllib2.urlopen(request,timeout=10)
  File "G:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "G:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "G:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "G:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "G:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11004] getaddrinfo failed>

*******2017-05-15 17:53:13.826000*************
       148 records has been stored in MySQL 
*******2017-05-15 17:53:29.881000*************
       148 records has been stored in MySQL 
*******2017-05-15 17:54:05.964000*************
       148 records has been stored in MySQL 
*******2017-05-15 17:55:07.615000*************
 no new datas have been crawed :http://xm.anjuke.com/sale/p13-rd1/?kw=%E8%8E%B2%E8%8A%B1%E5%A4%A7%E5%8E%A6&from_url=kw_final#filtersort. 

*******2017-05-15 17:55:20.282000*************
 no new datas have been crawed :http://xm.anjuke.com/sale/p12-rd1/?kw=%E8%8E%B2%E8%8A%B1%E5%A4%A7%E5%8E%A6&from_url=kw_final#filtersort. 

*******2017-05-15 17:55:35.679000*************
 no new datas have been crawed :http://xm.anjuke.com/sale/p11-rd1/?kw=%E8%8E%B2%E8%8A%B1%E5%A4%A7%E5%8E%A6&from_url=kw_final#filtersort. 

*******2017-05-15 17:59:19.315000*************
       148 records has been stored in MySQL 
*******2017-05-15 18:00:27.425000*************
       148 records has been stored in MySQL 
*******2017-05-15 18:00:58.968000*************
       148 records has been stored in MySQL 
*******2017-05-15 18:01:49.497000*************
       148 records has been stored in MySQL 
               *******craw_oneurl*******,error record by @mylog on 2017-05-16 08:20:02.655000*************
Traceback (most recent call last):
  File "E:\git\spider\mytools.py", line 11, in _deco
    return func(*a,**b)
  File "E:\git\house4.py", line 98, in craw_oneurl
    self.delay = int(new_urls)               # 调整延时值
ValueError: invalid literal for int() with base 10: ''

*******2017-05-16 08:22:31.138000*************
       148 records has been stored in MySQL 
*******2017-05-16 08:22:49.735000*************
       148 records has been stored in MySQL 
*******2017-05-16 08:23:22.561000*************
       199 records has been stored in MySQL 
*******2017-05-16 08:26:46.434000*************
 no new datas have been crawed :http://xm.anjuke.com/sale/p46-rd1/?kw=%E9%87%91%E5%B1%B1%E5%B0%8F%E5%8C%BA&from_url=kw_final#filtersort. 

*******2017-05-16 08:26:52.364000*************
 no new datas have been crawed :http://xm.anjuke.com/sale/p46-rd1/?kw=%E9%87%91%E5%B1%B1%E5%B0%8F%E5%8C%BA&from_url=kw_final#filtersort. 

*******2017-05-16 08:27:03.695000*************
       199 records has been stored in MySQL 
*******2017-05-16 08:27:17.248000*************
       199 records has been stored in MySQL 
*******2017-05-16 08:27:19.777000*************
       199 records has been stored in MySQL 
*******2017-05-16 08:27:22.671000*************
       199 records has been stored in MySQL 
*******2017-05-16 08:28:12.464000*************
       199 records has been stored in MySQL 
*******2017-05-16 08:51:05.582000*************
       199 records has been stored in MySQL 
*******2017-05-16 08:51:11.350000*************
 no new datas have been crawed :http://xm.anjuke.com/sale/p1-rd1/?kw=%E8%88%AA%E7%A9%BA%E5%88%AB%E5%A2%85&from_url=kw_final#filtersort. 

*******2017-05-16 08:51:59.729000*************
       199 records has been stored in MySQL 
*******2017-05-16 08:52:49.573000*************
       199 records has been stored in MySQL 
*******2017-05-16 08:53:15.431000*************
       199 records has been stored in MySQL 
*******2017-05-16 08:56:10.618000*************
 no new datas have been crawed :http://xm.anjuke.com/sale/p22-rd1/?kw=%E5%9B%BD%E9%99%85%E5%B1%B1%E5%BA%84&from_url=kw_final#filtersort. 

*******2017-05-16 08:56:29.983000*************
       199 records has been stored in MySQL 
*******2017-05-16 08:59:29.572000*************
       199 records has been stored in MySQL 
*******2017-05-16 09:00:52.784000*************
       199 records has been stored in MySQL 
*******2017-05-16 09:01:09.194000*************
       199 records has been stored in MySQL 
*******2017-05-16 09:01:14.230000*************
 no new datas have been crawed :http://xm.anjuke.com/sale/p1-rd1/?kw=%E6%96%87%E5%85%B4%E4%B8%9C%E4%B8%80%E9%87%8C1-26%E5%8F%B7&from_url=kw_final#filtersort. 

*******2017-05-16 09:01:19.652000*************
 no new datas have been crawed :http://xm.anjuke.com/sale/p1-rd1/?kw=%E6%96%87%E5%85%B4%E4%B8%9C%E4%B8%80%E9%87%8C1-26%E5%8F%B7&from_url=kw_final#filtersort. 

*******2017-05-16 09:01:23.061000*************
 no new datas have been crawed :http://xm.anjuke.com/sale/p1-rd1/?kw=%E6%96%87%E5%85%B4%E4%B8%9C%E4%B8%80%E9%87%8C1-26%E5%8F%B7&from_url=kw_final#filtersort. 

*******2017-05-16 09:01:30.570000*************
 no new datas have been crawed :http://xm.anjuke.com/sale/p1-rd1/?kw=%E6%96%87%E5%85%B4%E4%B8%9C%E4%B8%80%E9%87%8C1-26%E5%8F%B7&from_url=kw_final#filtersort. 

*******2017-05-16 09:01:37.990000*************
 no new datas have been crawed :http://xm.anjuke.com/sale/p1-rd1/?kw=%E6%96%87%E5%85%B4%E4%B8%9C%E4%B8%80%E9%87%8C1-26%E5%8F%B7&from_url=kw_final#filtersort. 

*******2017-05-16 09:01:37.991000*************
       199 records has been stored in MySQL 
*******2017-05-16 09:02:39.078000*************
       199 records has been stored in MySQL 
*******2017-05-16 09:05:06.354000*************
       199 records has been stored in MySQL 
*******2017-05-16 09:05:25.873000*************
       199 records has been stored in MySQL 
*******2017-05-16 09:08:50.912000*************
       199 records has been stored in MySQL 
*******2017-05-16 09:09:40.045000*************
       199 records has been stored in MySQL 
*******2017-05-16 09:09:53.671000*************
       199 records has been stored in MySQL 
*******2017-05-16 09:10:25.351000*************
       199 records has been stored in MySQL 
*******2017-05-16 09:10:53.597000*************
       199 records has been stored in MySQL 
*******2017-05-16 09:16:22.462000*************
       353 records has been stored in MySQL 
*******2017-05-16 09:17:47.155000*************
       353 records has been stored in MySQL 
*******2017-05-16 09:18:32.065000*************
       353 records has been stored in MySQL 